### ISSUE TITLE
Image out of mat-card element

### ISSUE THREAD

**Issue by pbennyjoseph** [Ismaestro/angular8-example-app#51]
**Description**
Image out of mat-card element 

**To Reproduce**
1. Go to the Homepage
2. Click on any of the images of heroes
3. You will be linked to the page 'hero detail'

**Expected behavior**
The image would look nice if inside the mat-card

**Screenshots**
Please look at the following screenshot

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Opera
 - Version 62.0.3331.72
![Annotation 2019-07-16 181000](https://user-images.githubusercontent.com/52366619/61295541-e4440580-a7f5-11e9-8653-ece8900d72a0.png)

**Comment by Ismaestro** [comment]
[Fixed](https://github.com/Ismaestro/angular8-example-app/commit/31176a8b2c34f2346fc5d0a9cfd9dff807b94667)!
